apiVersion: v1
kind: Pod
metadata: 
  name: podwithmultiport
  labels:
    name: PodwithMultiPort
    environment: production
    tier: front-end
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    - containerPort: 443
    - containerPort: 8080
