apiVersion: v1
kind: Pod
metadata:
    name: ofl-empty-dir-pod
spec:
    containers:
    - name: ofl-empty-dir-pod
      image: busybox
      command: ['sh', '-c', 'while true; do echo Success! >> /output/output.txt; sleep 5; done']
      volumeMounts:
      - name: output-vol
        mountPath: /output
    volumes:
    - name: output-vol
      hostPath:
        path: /var/datas