---
apiVersion: v1
kind: Pod
metadata:
  name: multicontainerpod
  labels:
    name: multi-container-pod
    environment: production
    tier: front-end
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
  - name: sidecar-logger
    image: busybox
    command: ["sh", "-c", "while true; do echo $(date) - Log from sidecar; sleep 100; done"]
