apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    name: multi-container-pod
    zone: Dev
    tier: front-end
spec:
  containers:
  - name: container1
    image: nginx
    
  - name: container2
    image: redis
    
  - name: container3
    image: memcached