---
apiVersion: v1
kind: Pod
metadata:
  name: multicontainerpod
  labels:
    name: multi-container-pod
    environment: production
    tier: front-end
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
  - name: sidecar
    image: curlimages/curl:latest
    command: ["sh", "-c", "while true; do curl localhost:80; sleep 300; done"]
