---
apiVersion: v1
kind: Pod
metadata: 
  name: webserver
  labels:
    name: webserver
    environment: production
    tier: front-end
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80

